# Generated by Django 5.0.3 on 2024-05-07 11:17

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(help_text='Enter the text here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.TextField(verbose_name=main_app.models.Author),
        ),
    ]
