# Generated by Django 5.0.3 on 2024-05-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_author_born_date_alter_author_description_and_more_'),
    ]

    operations = [
        #migrations.AlterField(
        # #   model_name='quote',
       #     name='author',
      #      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.author'),
      #  ),
    ]
