# Generated by Django 5.0.3 on 2024-05-07 12:27

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(verbose_name=main_app.models.Author),
        ),
    ]
