# Generated by Django 5.0.3 on 2024-05-07 13:06

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_quote_author_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.TextField(verbose_name=main_app.models.Author),
        ),
    ]
