# Generated by Django 5.0.3 on 2024-05-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_quote_author'),
    ]

    operations = [
        ##    model_name='quote',
        #    name='id',
        #),
        #migrations.AlterField(
       #     model_name='quote',
       #     name='author',
        #    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.author'),
        #),
    ]
